name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew buildPlugin
          ./gradlew nodeSetup
          ./gradlew yarn
          ./gradlew yarn_build
      - name: Commit new release
        env:
          INTELLIJ_DEPLOY: ${{ secrets.INTELLIJ_DEPLOY }}
        run: |
          VERSION=`./gradlew yarn_bump`
          git config --global user.name 'lukasbachbot'
          git config --global user.email 'bot@noreply.lukasbach.com'
          git status
          git add .
          git push
        #git tag $VERSION
        #git commit -m "Releasing"
        #./gradlew publishPlugin
